Netpoints/Netpoints/Controllers/EnlacesController.cs
using Entidades;
using Negocios;
using Netpoints.Filters;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Netpoints.Controllers
{
    public class EnlacesController : Controller
    {
        // GET: Enlaces
        //Autorizar acceso al modulo
        [AuthorizeUser(idmodulo: 11)]
        public ActionResult Index()
        {
            NEnlaces Negocios = new NEnlaces();
            List<EEnlaces> Lista = new List<EEnlaces>();
            Lista = Negocios.Mostrar();
            return View(Lista);
        }
        // Autorizar acceso a la accion
        [AuthorizeUserPermises(accion: "A", idmodulo: 11)]
        public ActionResult Agregar(EEnlaces Modelo)
        {
            try
            {
                NOficinas Oficinas = new NOficinas();
                NRedes Redes = new NRedes();
                NProveedores Proveedores = new NProveedores();
                NEnlaces Enlaces = new NEnlaces();
                ViewBag.ddlOficinas = Oficinas.Mostrar();
                ViewBag.ddlRedes = Redes.Mostrar();
                ViewBag.ddlProveedores = Proveedores.Mostrar(); 
                if (Modelo.IdOficina == 0 && Modelo.IdEnlace == 0)
                {
                    return View();
                }
                EUsuario User = (EUsuario)Session["User"];
                int FilasAfectadas = Enlaces.Agregar(Modelo,User.IdUsuario);
                if (FilasAfectadas > 0)
                {
                    return Json("success");
                }
                else
                {
                    return Json("Error");
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("Error", ex.Message);
                return Json("Error");
            }
        }
        // Autorizar acceso a la accion
        [AuthorizeUserPermises(accion: "E", idmodulo: 11)]
        public ActionResult Edit(string Id)
        {
            #region Llenar drop down oficinas
            NOficinas Negociosofi = new NOficinas();
            var lista1 = Negociosofi.Mostrar();
            var items = new SelectList(lista1, "IdOficina", "NombreOficina");
            ViewBag.ddloficinas = items;
            #endregion
            #region Llenar drop down redes
            NRedes Negociosredes = new NRedes();
            var listaredes = Negociosredes.Mostrar();
            var itemsredes = new SelectList(listaredes, "IdRed", "Linea");
            ViewBag.ddlredes = itemsredes;
            #endregion
            #region Llenar drop down proveedores
            NProveedores Negociosprov = new NProveedores();
            var listaprov = Negociosprov.Mostrar();
            var itemsprov = new SelectList(listaprov, "IdProveedor", "NombreEmpresa");
            ViewBag.ddlproveedores = itemsprov;
            #endregion
            NEnlaces Negocios = new NEnlaces();
            var Modelo = Negocios.Mostrar_Detallado(int.Parse(Id));
            ViewBag.Oficinas = Oficinas(Modelo.IdOficina.ToString());
            ViewBag.Redes = Redes(Modelo.IdRed.ToString());
            ViewBag.Proveedores = Proveedores(Modelo.IdProveedor.ToString());
            return View(Modelo);
        }
        // Autorizar acceso a la accion
        [AuthorizeUserPermises(accion: "E", idmodulo: 11)]
        [HttpPost]
        public ActionResult Edit(EEnlaces Modelo)
        {
            try
            {
                NEnlaces Negocios = new NEnlaces();
                EUsuario User = (EUsuario)Session["User"];
                int FilasAfectadas = Negocios.Modificar(Modelo,User.IdUsuario);
                if (FilasAfectadas > 0)
                {
                    return Json("success");
                }
                else
                {
                    return Json("Error");
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("Error", ex.Message);
                return Json("Error");
            }
        }
        // Autorizar acceso a la accion
        [AuthorizeUserPermises(accion: "D", idmodulo: 11)]
        [HttpGet]
        public ActionResult Delete(string id)
        {
            try
            {
                NEnlaces Negocios = new NEnlaces();
                EUsuario User = (EUsuario)Session["User"];
                int FilasAfectadas = Negocios.Eliminar(int.Parse(id),User.IdUsuario);
                if (FilasAfectadas > 0)
                {
                    TempData["msg"] = "0";
                }
                else
                {
                    TempData["msg"] = "-1";
                }
                return RedirectToAction("index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("Error", ex.Message);
                return Redirect("Index");
            }
        }
        public static EOficinas Oficinas(string Id)
        {
            try
            {
                NOficinas Negocios = new NOficinas();
                var Obj = Negocios.Mostrar_Detallado(int.Parse(Id));
                return Obj;
            }
            catch (Exception ex)
            {
                return null;
            }
        }
        public static ERedes Redes(string Id)
        {
            try
            {
                NRedes Negocios = new NRedes();
                var Obj = Negocios.Mostrar_Detallado(int.Parse(Id));
                return Obj;
            }
            catch (Exception ex)
            {
                return null;
            }
        }
        public static EProveedores Proveedores(string Id)
        {
            try
            {
                NProveedores Negocios = new NProveedores();
                var Obj = Negocios.Mostrar_Detallado(int.Parse(Id));
                return Obj;
            }
            catch (Exception ex)
            {
                return null;
            }
        }
        public ActionResult TraerOficina(string Id)
        {
            try
            {
                NOficinas Negocios = new NOficinas();
                var Obj = Negocios.Mostrar_Detallado(int.Parse(Id));
                if(Obj==null)
                {
                    return Json("Error", JsonRequestBehavior.AllowGet);
                }
                return Json(Obj, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("Error", ex.Message);
                return Json("Error");
            }
        }
        public ActionResult TraerRedes(string Id)
        {
            try
            {
                NRedes Negocios = new NRedes();
                var Obj = Negocios.Mostrar_Detallado(int.Parse(Id));
                if (Obj == null)
                {
                    return Json("Error", JsonRequestBehavior.AllowGet);
                }
                return Json(Obj, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("Error", ex.Message);
                return Json("Error");
            }
        }
    }
}

Netpoints/Netpoints/Views/Enlaces/Agregar.cshtml
@model Entidades.EEnlaces

@{
    ViewBag.Title = "Agregar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div id="EnlacesEdit" class="container">

    <div class="row" v-if="true">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Nuevo Enlace</h4>
                    <form id="FormEnlaces" action="/Enlaces/Agregar" method="POST">

                        <input type="hidden" name="IdEnlace" v-model="model.IdEnlace" />

                        <div class="form-floating mb-3 form-group">
                            <select class="form-control" id="IdOficina" name="IdOficina" arial-label="Default select example" onchange="ChangeOficina()" required>
                                <option value="">Seleccionar</option>
                                @foreach (var item in ViewBag.ddlOficinas)
                                {
                                    <option value="@item.IdOficina">@item.NombreOficina</option>
                                }
                            </select>
                            <label for="IdOficina">Sitio</label>
                        </div>
                        <div class="form-floating mb-3 form-group">
                            <input class="form-control" type="text" name="UE" id="UE" placeholder="Unidad Ejecutora" readonly required />
                            <label for="UE">Unidad Ejecutora</label>
                        </div>
                        <div class="form-floating mb-3 form-group">
                            <input class="form-control" type="text" name="Provincia" id="Provincia" placeholder="Provincia" readonly required />
                            <label for="Provincia">Provincia</label>
                        </div>
                        <div class="form-floating mb-3 form-group">
                            <input class="form-control" type="text" name="Comentariob" id="Comentariob" placeholder="Comentario" readonly />
                            <label for="Comentariob">Comentario</label>
                        </div>
                        <div class="form-floating mb-3 form-group">
                            <select class="form-control" id="IdRed" name="IdRed" arial-label="Default select example" onchange="ChangeLinea()" required>
                                <option value="">Seleccionar</option>
                                @foreach (var item in ViewBag.ddlRedes)
                                {
                                    <option value="@item.IdRed">@item.Linea</option>
                                }
                            </select>
                            <label for="Redes">Número de Linea</label>
                        </div>
                        <div class="form-floating mb-3 form-group">
                            <input class="form-control" type="text" name="Gateway" id="Gateway" placeholder="IP Gateway" readonly />
                            <label for="Gateway">IP Gateway</label>
                        </div>
                        <div class="form-floating mb-3 form-group">
                            <input class="form-control" type="text" name="Interface" id="Interface" placeholder="Interface" readonly />
                            <label for="Gateway">Interface</label>
                        </div>
                        <div class="form-floating mb-3 form-group">
                            <input class="form-control" type="text" name="TipoEnlace" id="TipoEnlace" placeholder="Tipo Enlace" readonly />
                            <label for="TipoEnlace">Tipo Enlace</label>
                        </div>
                        <div class="form-floating mb-3 form-group">
                            <input class="form-control" type="text" name="Bandwidth" id="Bandwidth" placeholder="Bandwidth" readonly />
                            <label for="Bandwidth">Bandwidth</label>
                        </div>
                        <div class="form-floating mb-3 form-group">
                            <input class="form-control" type="text" name="MedioEnlace" id="MedioEnlace" placeholder="Medio Enlace" readonly />
                            <label for="MedioEnlace">Medio Enlace</label>
                        </div>
                        <div class="form-floating mb-3 form-group">
                            <input class="form-control" type="text" name="Comentarioa" id="Comentarioa" placeholder="Comentario" readonly />
                            <label for="Comentarioa">Comentario</label>
                        </div>
                        <div class="form-floating mb-3 form-group">
                            <select class="form-control" id="IdProveedor" name="IdProveedor" arial-label="Default select example" required>
                                @foreach (var item in ViewBag.ddlProveedores)
                                {
                                    <option value="@item.IdProveedor">@item.NombreEmpresa</option>
                                }
                            </select>
                            <label for="Proveedores">Proveedor</label>
                        </div>
                        <div class="form-floating mb-3 form-group">
                            <textarea class="form-control" type="text" name="Comentario" id="textarea" rows="3"> </textarea>
                            <label for="Comentario"> Comentarios </label>
                        </div>
                        <br />
                        <div class="mb-3">
                            <button type="submit" class="btn btn-outline-primary" id="Aceptar">Guardar <i class='bx bx-save'></i></button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@section scripts{
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/Enlaces/Agregar.js" defer></script>
    <script>CreateValidator("#EnlacesEdit");</script>
    <script>
        function ChangeOficina() {
            if ($('#IdOficina').val() != "") {
                $.ajax({
                    type: "GET",
                    url: "@Url.Action("TraerOficina", "Enlaces")" + "?" + "id=" + $('#IdOficina').val(),
                    cache: false,
                    contentType: false,
                    processData: false,
                    success: function (data) {
                        Loading.fire("Cargando...");
                        if (data == "Error") {
                            Loading.close();
                            Toast.fire({
                                icon: 'error',
                                title: 'Error'
                            });
                        }
                        if (data != "") {
                            //debugger
                            Loading.close();
                            $('#UE').val(data['UE']);
                            $('#Provincia').val(data['Provincia']);
                            $('#Comentariob').val(data['Comentario']);
                        }
                    },
                    error: function (xhr, error, status) {
                        Loading.close();
                        Toast.fire({
                            icon: 'error',
                            title: 'Error'
                        });
                    },
                });
            } else {
                $('#UE').val("");
                $('#Provincia').val("");
                $('#Comentariob').val("");
            }
        }
        function ChangeLinea() {
            if ($('#IdRed').val() != "") {
                $.ajax({
                    type: "GET",
                    url: "@Url.Action("TraerRedes", "Enlaces")" + "?" + "id=" + $('#IdRed').val(),
                    cache: false,
                    contentType: false,
                    processData: false,
                    success: function (data) {
                        Loading.fire("Cargando...");
                        if (data == "Error") {
                            Loading.close();
                            Toast.fire({
                                icon: 'error',
                                title: 'Error'
                            });
                        }
                        if (data != "") {
                            Loading.close();
                            $('#Gateway').val(data['Gateway']);
                            $('#Interface').val(data['Interface']);
                            $('#TipoEnlace').val(data['TipoEnlace']);
                            $('#MedioEnlace').val(data['MedioEnlace']);
                            $('#Bandwidth').val(data['Bandwidth']);
                            $('#Comentarioa').val(data['Comentario']);
                        }
                    },
                    error: function (xhr, error, status) {
                        Loading.close();
                        Toast.fire({
                            icon: 'error',
                            title: 'Error'
                        });
                    },
                });
            } else {
                $('#Gateway').val("");
                $('#Interface').val("");
                $('#TipoEnlace').val("");
                $('#Bandwidth').val("");
                $('#MedioEnlace').val("");
                $('#Comentarioa').val("");
                $('#Bandwidth').val("");
            }
        }
    </script>
}

Netpoints/Netpoints/Views/Enlaces/Edit.cshtml
@model Entidades.EEnlaces

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="EnlacesEdit" class="container">

    <div class="row" v-if="true">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Editar Enlace</h4>
                    <form id="FormEnlaces" action="/Enlaces/Edit" method="POST">

                        <input type="hidden" name="IdEnlace" value="@Model.IdEnlace" />

                        <div class="form-floating mb-3 form-group">
                            @Html.DropDownList("IdOficina", ViewBag.ddloficinas as SelectList, new { @class = "form-control", @required = "required", @onchange = "ChangeOficina()" })
                            <label for="IdOficina">Sitio</label>
                        </div>
                        <div class="form-floating mb-3 form-group">
                            <input class="form-control" type="text" name="UE" id="UE" placeholder="Unidad Ejecutora" value="@ViewBag.Oficinas.UE" readonly required />
                            <label for="UE">Unidad Ejecutora</label>
                        </div>
                        <div class="form-floating mb-3 form-group">
                            <input class="form-control" type="text" name="Provincia" id="Provincia" placeholder="Provincia" value="@ViewBag.Oficinas.Provincia" readonly required />
                            <label for="Provincia">Provincia</label>
                        </div>
                        <div class="form-floating mb-3 form-group">
                            <input class="form-control" type="text" name="Comentariob" id="Comentariob" placeholder="Comentario" value="@ViewBag.Oficinas.Comentario"  readonly />
                            <label for="Comentariob">Comentario</label>
                        </div>
                        <div class="form-floating mb-3 form-group">
                            @Html.DropDownList("IdRed", ViewBag.ddlredes as SelectList, new { @class = "form-control", @required = "required", onchange = "ChangeLinea()" })
                            <label for="IdRed">Número de Linea</label>
                        </div>
                        <div class="form-floating mb-3 form-group">
                            <input class="form-control" type="text" name="Gateway" id="Gateway" placeholder="IP Gateway" value="@ViewBag.Redes.Gateway" readonly />
                            <label for="Gateway">IP Gateway</label>
                        </div>
                        <div class="form-floating mb-3 form-group">
                            <input class="form-control" type="text" name="Interface" id="Interface" placeholder="Interface" value="@ViewBag.Redes.Interface" readonly />
                            <label for="Gateway">Interface</label>
                        </div>
                        <div class="form-floating mb-3 form-group">
                            <input class="form-control" type="text" name="TipoEnlace" id="TipoEnlace" placeholder="Tipo Enlace" value="@ViewBag.Redes.TipoEnlace" readonly />
                            <label for="TipoEnlace">Tipo Enlace</label>
                        </div>
                        <div class="form-floating mb-3 form-group">
                            <input class="form-control" type="text" name="Bandwidth" id="Bandwidth" placeholder="Bandwidth" value="@ViewBag.Redes.Bandwidth" readonly />
                            <label for="Bandwidth">Bandwidth</label>
                        </div>
                        <div class="form-floating mb-3 form-group">
                            <input class="form-control" type="text" name="MedioEnlace" id="MedioEnlace" placeholder="Medio Enlace" value="@ViewBag.Redes.MedioEnlace" readonly />
                            <label for="MedioEnlace">Medio Enlace</label>
                        </div>
                        <div class="form-floating mb-3 form-group">
                            <input class="form-control" type="text" name="Comentarioa" id="Comentarioa" placeholder="Comentario" value="@ViewBag.Redes.Comentario" readonly />
                            <label for="Comentarioa">Comentario</label>
                        </div>
                        <div class="form-floating mb-3 form-group">
                            @Html.DropDownList("IdProveedor", ViewBag.ddlproveedores as SelectList, new { @class = "form-control", @required = "required" })
                            <label for="IdProveedor">Proveedor</label>
                        </div>
                        <div class="form-floating mb-3 form-group">
                            <textarea class="form-control" type="text" name="Comentario" id="textarea" rows="3">@Model.Comentario </textarea>
                            <label for="Comentario"> Comentarios </label>
                        </div>
                        <br />
                        <div class="mb-3">
                            <button type="submit" class="btn btn-outline-primary">Guardar <i class='bx bx-edit'></i></button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@section scripts{
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/Enlaces/Edit.js" defer></script>
    <script>CreateValidator("#EnlacesEdit");</script>
    <script>
        function ChangeOficina() {
            if ($('#IdOficina').val() != "") {
                $.ajax({
                    type: "GET",
                    url: "@Url.Action("TraerOficina", "Enlaces")" + "?" + "id=" + $('#IdOficina').val(),
                    cache: false,
                    contentType: false,
                    processData: false,
                    success: function (data) {
                        Loading.fire("Cargando...");
                        if (data == "Error") {
                            Loading.close();
                            Toast.fire({
                                icon: 'error',
                                title: 'Error'
                            });
                        }
                        if (data != "") {
                            //debugger
                            Loading.close();
                            $('#UE').val(data['UE']);
                            $('#Provincia').val(data['Provincia']);
                            $('#Comentariob').val(data['Comentario']);
                        }
                    },
                    error: function (xhr, error, status) {
                        Loading.close();
                        Toast.fire({
                            icon: 'error',
                            title: 'Error'
                        });
                    },
                });
            } else {
                $('#UE').val("");
                $('#Provincia').val("");
                $('#Comentariob').val("");
            }
        }
        function ChangeLinea() {
            if ($('#IdRed').val() != "") {
                $.ajax({
                    type: "GET",
                    url: "@Url.Action("TraerRedes", "Enlaces")" + "?" + "id=" + $('#IdRed').val(),
                    cache: false,
                    contentType: false,
                    processData: false,
                    success: function (data) {
                        Loading.fire("Cargando...");
                        if (data == "Error") {
                            Loading.close();
                            Toast.fire({
                                icon: 'error',
                                title: 'Error'
                            });
                        }
                        if (data != "") {
                            Loading.close();
                            $('#Gateway').val(data['Gateway']);
                            $('#Interface').val(data['Interface']);
                            $('#TipoEnlace').val(data['TipoEnlace']);
                            $('#MedioEnlace').val(data['MedioEnlace']);
                            $('#Bandwidth').val(data['Bandwidth']);
                            $('#Comentarioa').val(data['Comentario']);
                        }
                    },
                    error: function (xhr, error, status) {
                        Loading.close();
                        Toast.fire({
                            icon: 'error',
                            title: 'Error'
                        });
                    },
                });
            } else {
                $('#Gateway').val("");
                $('#Interface').val("");
                $('#TipoEnlace').val("");
                $('#Bandwidth').val("");
                $('#MedioEnlace').val("");
                $('#Comentarioa').val("");
                $('#Bandwidth').val("");
            }
        }
    </script>
}

Netpoints/Netpoints/Views/Enlaces/Index.cshtml
@model IEnumerable<Entidades.EEnlaces>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container-fluid">
    <h1>Enlaces</h1> <br />
    <div class="row">
        <div class="col-2">
            <button type="button" class="btn btn-outline-primary" onclick="ClickNew()"><i class='bx bx-add-to-queue'></i>Agregar</button>
            <br />
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-12">
            <table id="GridEnlaces" class="table table-dark table-hover">
                <thead>
                    <tr>
                        <th>Provincia</th>
                        <th>Sitio</th>
                        <th>Unidad Ejecutora</th>
                        <th>Número de Linea</th>
                        <th>IP Gateway</th>
                        <th>Interface</th>
                        <th>Tipo Enlace</th>
                        <th>Bandwidth</th>
                        <th>Medio Enlace</th>
                        <th>Proveedor</th>
                        <th>Comentario</th>
                        <th>Acción</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                    <tr>
                        <td>@Netpoints.Controllers.EnlacesController.Oficinas(item.IdOficina.ToString()).Provincia</td>
                        <td>@Netpoints.Controllers.EnlacesController.Oficinas(item.IdOficina.ToString()).NombreOficina</td>
                        <td>@Netpoints.Controllers.EnlacesController.Oficinas(item.IdOficina.ToString()).UE</td>
                        <td>@Netpoints.Controllers.EnlacesController.Redes(item.IdRed.ToString()).Linea</td>
                        <td>@Netpoints.Controllers.EnlacesController.Redes(item.IdRed.ToString()).Gateway</td>
                        <td>@Netpoints.Controllers.EnlacesController.Redes(item.IdRed.ToString()).Interface</td>
                        <td>@Netpoints.Controllers.EnlacesController.Redes(item.IdRed.ToString()).TipoEnlace</td>
                        <td>@Netpoints.Controllers.EnlacesController.Redes(item.IdRed.ToString()).Bandwidth</td>
                        <td>@Netpoints.Controllers.EnlacesController.Redes(item.IdRed.ToString()).MedioEnlace</td>
                        <td>@Netpoints.Controllers.EnlacesController.Proveedores(item.IdProveedor.ToString()).NombreEmpresa</td>
                        <td>@item.Comentario</td>
                        <td>
                            <button type="button" class="btn btn-outline-primary" onclick="ClickUpdate(@item.IdEnlace)"><i class='bx bxs-edit'></i>Editar</button>
                            <button type="button" class="btn btn-outline-primary" onclick="ClickDelete(@item.IdEnlace)"><i class='bx bxs-trash'></i>Eliminar</button>

                        </td>
                    </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

<div id="root">

</div>

@section scripts{
    @if (TempData["msg"] == "0")
    {
        <script>
            Swal.fire(
                '¡Eliminado!',
                'El Enlace ha sido Eliminado.',
            );
            var IsLoading = false;
        </script>
    }
    else
    {
        <script>
            var IsLoading = true;
        </script>
    }
    <script src="~/Scripts/Enlaces/Index.js"></script>
}